version: '3.7'

services:
    server:
        build: .
        restart: always
        command:
            - entrypoint.sh
        volumes:
            - .:/code
        ports:
            - 8000:8000
        env_file:
            - ./.env
        depends_on:
            - db
    db:
        image: postgres:12-alpine
        env_file:
            - ./.env